---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-volume
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.config.storage.capacity }}
  accessModes: {{ .Values.config.storage.accessModes }}
  hostPath:
    path: {{ .Values.config.storage.hostPath }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  {{ .Release.Name }}-pv-claim
spec:
  storageClassName: manual
  resources:
    requests:
      storage: {{ .Values.config.storage.capacity }}
  volumeMode: Filesystem
  accessModes: {{ .Values.config.storage.accessModes }}
